import { Inter } from "next/font/google";
import { NextAuthProvider } from "./providers.jsx";
import StoreProvider from "./StoreProvider.jsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <NextAuthProvider>{children}</NextAuthProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
